nasa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'
urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^search_tags/$', views.search_tags_view, name='search_tags'),
    url(r'^fastsearch/$', views.fastsearch_view, name='fastsearch'),
    url(r'^search/$', views.search_view, name='search'),
]

web/models.py
from django.db import models

# Create your models here.

web/views.py
import urllib.request
import json
import html
import datetime
import numpy as np

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

def escape(word):
	return word.replace(' ', '%20')

def get_images(searchword, title=None, date_range=None, location=None, photographer=None):
	root = 'https://images-api.nasa.gov'
	api = root + '/search?'
	if searchword:
		searchword = escape(searchword)
		api += 'q={0}'.format(searchword)
	else:
		api += 'q=NASA'
	if title:
		title = escape(title)
		print(title)
		api += '&title={0}'.format(html.escape(title))
	if date_range[0] != "" and date_range[1] != "": 
		date_range = (escape(date_range[0]), escape(date_range[1]))
		api += '&year_start={0}'.format(html.escape(date_range[0]))
		api += '&year_end={0}'.format(html.escape(date_range[1]))
	if location:
		location = escape(location)
		api += '&location={0}'.format(html.escape(location))
	if photographer:
		photographer = escape(photographer)
		api += '&photographer={0}'.format(html.escape(photographer))
	print(api)
	with urllib.request.urlopen(api) as url:
		data = json.loads(url.read().decode())
	i = 0
	ids = []
	titles = []
	descriptions = []
	src = []
	tags = []
	date_created = []
	for item in data["collection"]["items"]:
		if "links" not in item:
			continue
		if "title" in item["data"][0]:
			titles.append(item["data"][0]["title"])
		else:
			titles.append("")
		if "description" in item["data"][0]:
			descriptions.append(item["data"][0]["description"])
		else:
			descriptions.append("")

		if "keywords" in item["data"][0]:
			keywords = item["data"][0]["keywords"]
			if len(keywords):
				tmp = keywords[:min(3,len(keywords))]
				# tmp = [t[:20] + "..." if len(t) > 20 else t for t in tmp]
				tags.append(tmp)
			else:
				tags.append([])
		else:
			tags.append([])
		if "date_created" in item["data"][0]:
			date_created.append(datetime.datetime.strptime(item["data"][0]["date_created"],
				"%Y-%m-%dT%XZ").strftime("%B %d, %Y"))
		else:
			date_created.append([])
		for link in item["links"]:
			if link["rel"] == "preview":
				src.append(html.escape(link["href"]))
				break
		ids.append(i)
		i += 1
	ids += [-1]*((3 - (len(ids) % 3)) % 3)
	ids = np.array(ids).reshape((3, len(ids)//3)).tolist()
	return ids, titles, descriptions, tags, src, date_created

def index_view(request):
	data = {}
	return render(request, 'web/index.html', data)

def search_tags_view(request):
	data = {}
	tag = request.GET.get('tag', '')
	data['searchword'] = tag
	data['ids'], data['titles'], data['descriptions'], data['tags'], data['links'], data['date_created'] = get_images(
		tag, title="", date_range=("",""), location="", photographer=""
	)
	data['num_results'] = len(data['titles'])
	return render(request, 'web/results.html', data)

def fastsearch_view(request):
	data = {}
	searchword = request.POST['searchword']
	title = request.POST['title'].strip()
	location = request.POST['location'].strip()
	photographer = request.POST['location'].strip()
	date = (request.POST['start_date'].strip(), request.POST['end_date'].strip())
	data['searchword'] = searchword
	data['ids'], data['titles'], data['descriptions'], data['tags'], data['links'], data['date_created'] = get_images(
		searchword, title=title, date_range=date, location=location, photographer=photographer
	)
	data['num_results'] = len(data['titles'])
	return render(request, 'web/results.html', data)

def search_view(request):
	data = {}
	searchword = request.POST['searchword']
	title = request.POST['title'].strip()
	location = request.POST['location'].strip()
	photographer = request.POST['location'].strip()
	date = (request.POST['start_date'].strip(), request.POST['end_date'].strip())
	data['searchword'] = searchword
	data['ids'], data['titles'], data['descriptions'], data['tags'], data['links'], data['date_created'] = get_images(
		searchword, title=title, date_range=date, location=location, photographer=photographer
	)
	data['num_results'] = len(data['titles'])
	return render(request, 'web/results.html', data)

web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="HandheldFriendly" content="True">
        <meta name="author" content="Michael Wan">
        <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <style>
            html {
                position: fixed;
                min-width: 1024px;
                min-height: 768px;
                position: fixed;
                top: 0;
                width: 100%;
                height: 100%;
            }
            .container {display: table;}
            .masthead {
                color: white;
                display: table-cell;
                vertical-align: middle;
            }

            {% load static %}
            body {
                background-image: url("{% static 'background/nasa.jpg' %}");
                background-size: 100% 150%;
                background-repeat: no-repeat;
            }
            .container {
                padding: 100px 0px 0px 0px;
            }
            a.nostyle:link {
                text-decoration: inherit;
                color: inherit;
            }
            a.nostyle:visited {
                text-decoration: inherit;
                color: inherit;
            }
            a.nostyle:hover {
                /*transform: scale(1.1);*/
                color: #38cc76;
                /*font: bold;*/
                /*font-weight: bold;*/
            }
        </style>
    </head>
    <body>
        {% include "menu.html" %}
        <div class="container">
            <div class="masthead">
                <h1>NASA Image Database</h1>
                <h3>Stunning photos out of this world</h3>
                <form id='search' action="{% url 'web:fastsearch' %}" method="post">
                    {% csrf_token %}
                    <input type="text" size='40' name='searchword' id='searchword'
                        class="form-control mr-sm-2"
                        placeholder="Search..">
                    <input type="text" name='title' id='title' placeholder="" style='display: none'>
                    <input type="date" name='start_date' id='start_date' placeholder="" style='display: none'>
                    <input type="date" name='end_date' id='end_date' placeholder="" style='display: none'>
                    <input type="text" name='location' id='location' placeholder="" style='display: none'>
                    <input type="text" name='photographer' id='photographer' placeholder="" style='display: none'>
                    <button style="display:none" type="submit">Search</button>
                </form>
                <br>
                <p>Popular searches:
                    <i><a class='nostyle' href="{% url 'web:search_tags' %}?tag=NASA">NASA</a></i>,&nbsp;
                    <i><a class='nostyle' href="{% url 'web:search_tags' %}?tag=Mars">Mars</a></i>,&nbsp;
                    <i><a class='nostyle' href="{% url 'web:search_tags' %}?tag=Jupiter">Jupiter</a></i>,&nbsp;
                    <i><a class='nostyle' href="{% url 'web:search_tags' %}?tag=Earth">Earth</a></i>&nbsp;
                </p>
            </div>
        </div>
    </body>
</html>

web/templates/web/results.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="HandheldFriendly" content="True">
        <meta name="author" content="Michael Wan">
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/tingle.css' %}">
        {% load static %}
        <script src="{% static 'js/tingle.js' %}"></script>

        <style>
            .navbar {
                position: fixed;
                top: 0;
                width: 100%;
                z-index: 1;
            }
            .preview:hover {
                transform: scale(1.1);
                transition: transform .4s;
                cursor: pointer;
            }
            .preview {
                transform: scale(1.0);
                cursor: auto;
            }
            .tingle-modal-box {

            }
            .modal_container {
                position: relative;
                background: transparent;
                /*background: rgba(0, 0, 0, .8);*/
            }
            .tingle-modal-box__content {
                padding: 0px 0px;
                background: rgba(0, 0, 0, 0.0); /* Black see-through */
            }
            .tingle-modal-box__footer {
                width: auto;
                padding: 0px 0px;
                border-bottom-right-radius: 0px;
                border-bottom-left-radius: 0px;
                opacity: 0;
            }
            .tingle-modal img {
                background: white;
            }
            .tingle-modal .meta {
                color: black;
                font-size: 12px;
                margin: 5px 5px 5px 5px;
                background-color: transparent;
            }
            .download {
                cursor: auto
            }
            .download:hover {
                cursor: pointer;
            }
            a.nostyle:link {
                text-decoration: inherit;
                color: inherit;
            }
            a.nostyle:visited {
                text-decoration: inherit;
                color: inherit;
            }
        </style>
    </head>
    <body>
        {% load web_extras %}
        {% include "menu.html" %}
        <div class="container">
            <br><br><br><br><br>
            <h1 style="font-size: 300%">{{searchword}}</h1>
            {% if searchword != "" %}
                <i>{{num_results}} "{{searchword}}" results found</i><br><br>
            {% else %}
                <i>{{num_results}} results found</i><br><br>
            {% endif %}
            <div class="row">
                {% for row in "012" %}
                    <div class="col-sm-4">
                        {% for i in ids|index:row %}
                            {% if i != -1 %}
                                <div class="preview" id="preview_{{i}}" width="100%">
                                    <img src="{{links|index:i}}" width="90%"><br>
                                    <span id='title' width="90%">{{titles|index:i}}</span><br>
                                    <span id='date' style='display: none'>{{date_created|index:i}}</span>
                                    <span id='description' style='display: none'>{{descriptions|index:i}}</span>
                                    <a class='download_anchor' id='download_{{i}}' href='{{links|index:i}}' style='display: none' download></a>
                                    {% for tag in tags|index:i %}
                                        <span class='badge badge-dark'><a class='nostyle no_preview' href="{% url 'web:search_tags' %}?tag={{tag}}">{{tag}}</a></span>&nbsp;&nbsp;
                                    {% endfor %}
                                    <!-- <a class='heart badge badge-light' href='#' onclick='return false;'>
                                        <i class="far fa-heart start"></i>
                                        <i class="fas fa-heart hover" style="display: none"></i>
                                        <i class="fas fa-heart click" style="color: red; display: none"></i>
                                    </a> -->
                                </div>
                                <br><br><br>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </body>
    <script>
        $(document).ready(function() {
            $(".heart").hover(function() {
                if ($(this).children('.click').css('display') == 'none') {
                    $(this).children('.start').css('display', 'none');
                    $(this).children('.click').css('display', 'none');
                    $(this).children('.hover').css('display', 'inline');
                }
            }, function() {
                if ($(this).children('.click').css('display') == 'none')
                    $(this).children('.start').css('display', 'inline');   
                else
                    $(this).children('.start').css('display', 'none');
                $(this).children('.hover').css('display', 'none');
            });
            $(document).on('click', '.heart', function() {
                if ($(this).children('.click').css('display') == 'none') {
                    $(this).children('.start').css('display', 'none');
                    $(this).children('.hover').css('display', 'none');
                    $(this).children('.click').css('display', 'inline');
                }
                else {
                    $(this).children('.start').css('display', 'inline');
                    $(this).children('.hover').css('display', 'none');
                    $(this).children('.click').css('display', 'none');
                }
            })
            $(".no_preview").hover(function() {
                $(this).css('color', '#4684ED');
                openpreview = false;
            }, function() {
                $(this).css('color', 'white');
                openpreview = true;
            });
        });
        var modal = new tingle.modal({
            footer: true,
            stickyFooter: false,
            closeMethods: ['overlay', 'button', 'escape'],
            closeLabel: "Close",
            cssClass: ['custom-class-1', 'custom-class-2'],
            onOpen: function() {
            },
            onClose: function() {
            },
            beforeClose: function() {
                return true;
            }
        });
        function trigger_download(url) {
            window.open(url);
        }
        openpreview = true;
        $(document).on('click', '.preview', function() {
            if (openpreview) {
                img_src = $(this).children('img').attr('src');
                title = $(this).children('#title')[0].innerText;
                date = $(this).children('#date')[0].innerText;
                description = $(this).children('#description')[0].innerText;
                download = $(this).children('.download_anchor')[0].id;
                console.log(img_src);
                modal.setContent("<div class='modal_container'><img class='modal_img' src='" + img_src + "' width='100%'><br><div class='meta' style='text-align: left'><b><i>" + title + "</i></b><hr style='margin:7px'>Description: " + description + "<br><br><div style='line-height: 12px'><span style='line-height: 12px' class='badge badge-secondary'><i class='far fa-clock'></i>&nbsp;" + date + "</span></span></i><span onclick='trigger_download(\"" + img_src + "\")' class='download badge badge-primary' style='padding-left: 8px; padding-right: 8px; float: right; line-height: 12px'><i class='fas fa-file-download'></i>&nbsp;Download</span></div></div></div>");
                modal.open();
            }
        });
    </script>
</html>